name: github-actions
on: [push]

jobs:
  build:
    env:
      PA_TOKEN: ${{ secrets.PA_TOKEN}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python PythonAnywhereAPI.py