name: github-actions
on: [push]
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: fylein/python-pytest-github-action@v2
        with:
          args: pip3 install -r requirements.txt && PythonAnywhereAPI.py
