name: github-actions
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      api_token: ${{ secrets.PA_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          run: |
            python -m pip install --upgrade pip
            pip install  -r requirements.txt; fi
      - name: Display Python version
        run: python -m PythonAnywhereAPI.py