name: github-actions
on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        env:
          PA_TOKEN: ${{ secrets.PA_TOKEN}}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_CI.txt
          python pull_and_reload.py
